---
title: "Home"
output:
  html_document:
    toc: true
---

# Useful Links/Downloads

- There are two textbooks for this course
    - [OpenIntro](https://www.openintro.org/stat/textbook.php?stat_book=os): You can [download](https://www.openintro.org/download.php?file=os3&referrer=/stat/textbook.php) this textbook for FREE. In addition to the textbook, their website has additional lecture slides, video lectures, and labs for practicing R. This book will generally be used for everything but probability.
    - [From Algorithms to Z-Scores: Probabilistic and Statistical Modeling in Computer Science](http://heather.cs.ucdavis.edu/probstatbook): Again, this book can be [downloaded](http://heather.cs.ucdavis.edu/~matloff/132/PLN/probstatbook/ProbStatBook.pdf) entirely for free. This book will be useful for the more mathematical introduction to probability that is beyond the scope of OpenIntro.
- A fast, practical way to learn R is through the [swirl](http://swirlstats.com/) package. Follow the instructions from that link to go through a few tutorials.
- [Rstudio](https://www.rstudio.com/resources/cheatsheets/) has made some very useful cheat sheets that you can reference while you are programming in R. I've placed some of the more useful ones for this class here:
    - [Base R](./cheat_sheets/base-r.pdf)
    - [Data Wrangling](./cheat_sheets/data-transformation-cheatsheet.pdf)
    - [ggplot2](./cheat_sheets/ggplot2-cheatsheet-2.1.pdf)
    - [Data Import](./cheat_sheets/data-import-cheatsheet.pdf)
    - [Rstudio IDE](./cheat_sheets/rstudio-IDE-cheatsheet.pdf)
- In addition, I wrote up a brief cheat sheet for [R Base graphics](base_r_cheatsheet.html).
    

# Lectures 

Note: Each lecture is a topic, not a day of class.

1. [Course Outline](00_course_outline.pdf)
2. [Data Basics](01_data_basics.pdf)
3. [Histograms](02_histograms.pdf)
4. [Center/Spread](03_center_spread.pdf)
5. [Quantiles](04_quantiles.pdf)
6. [Categorical Variables](05_categorical_variables.pdf)
7. [Case Study: Trump's Tweets](06_trump_case.pdf)
8. [Densities](07_densities.pdf)
9. [Normal Density Calculations](08_normal_calculations.pdf)
10. [Sampling Distributions](09_distribution_sample_mean.pdf)
11. [Probability and Sets](10_probability_and_sets.pdf)
12. Proofs from Axioms of Probability
13. Conditional Probability and Independence
14. Discrete Random Variables
15. Continuous Random Variables
16. Moment Generating Functions
17. To be continued ...

# Stat Comics That Made Me Laugh
- SMBC:
    - [Effect size](http://www.smbc-comics.com/comic/bacon-is-literally-cancer)
    - [Allegorical Evidence](http://www.smbc-comics.com/comic/accuracy-in-kids39-shows)
    - [Hypothesis Testing](http://www.smbc-comics.com/comic/i-object)
    - [Bayesian Drinking](http://www.smbc-comics.com/comic/2014-05-23)
    - [Small Sample Size](http://www.smbc-comics.com/comic/2014-09-17)
    - [Type I Error Control](http://smbc-comics.com/comic/false-positives)
- XKCD:
    - [Outliers](https://xkcd.com/539/)
    - [Correlation and Causation](https://xkcd.com/552/)
    - [Extrapolation](https://xkcd.com/605/)
    - [Bad Plots](https://xkcd.com/833/)
    - [Publication Bias](https://xkcd.com/882/)
    - [Usually Use Proportions, not Counts](https://www.xkcd.com/1138/)
    - [p-values](https://www.xkcd.com/1478/)

